services:
  xml-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - /home/node/app/node_modules
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: xml-api
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
